import type { Metadata } from "next";
import "./globals.css";
import { TextButton } from "./_components/button";
import { CopyIcon } from "./_components/icons/copy";
import { Contact } from "./_components/contact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <div className="relative z-20 group flex gap-10 items-center justify-between text-white font-extrabold border-b border-white-transparent py-4 px-10 bg-gradient-to-l from-pink-200 to-pink-600">
          <div className="flex gap-10 items-center ">
            <h2>REBECCA FRANSSON</h2>
            <Contact />
          </div>
        </div>

        <div className="flex justify-center">{children}</div>
      </body>
    </html>
  );
}
